name: Build and Deploy Jekyll Pages

on:
  # Runs on pushes targeting the default branch (main)
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.x # Choose the Ruby version you need

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Build Jekyll Site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: _site

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll-site/_site
