name: Build and Deploy Jekyll Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby and Node
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_pages
